import { Question, QuestionDifficulty, QuestionType, ProgrammingLanguage } from '../types';
import { v4 as uuidv4 } from 'uuid';

export class QuestionService {
  private sampleQuestions: Question[] = [
    {
      id: uuidv4(),
      type: 'multiple-choice',
      difficulty: 'easy',
      language: 'python',
      title: 'Python Basics',
      content: 'What is the correct way to create a list in Python?',
      options: ['list = []', 'list = ()', 'list = {}', 'list = ""'],
      correctAnswer: 'list = []',
      explanation: 'In Python, lists are created using square brackets []',
      timeLimit: 30,
      points: 10
    },
    {
      id: uuidv4(),
      type: 'multiple-choice',
      difficulty: 'easy',
      language: 'java',
      title: 'Java Basics',
      content: 'Which keyword is used to create a class in Java?',
      options: ['class', 'Class', 'struct', 'object'],
      correctAnswer: 'class',
      explanation: 'The "class" keyword is used to define a class in Java',
      timeLimit: 30,
      points: 10
    },
    {
      id: uuidv4(),
      type: 'multiple-choice',
      difficulty: 'medium',
      language: 'cpp',
      title: 'C++ Pointers',
      content: 'What does the * operator do when used with a pointer?',
      options: ['Creates a pointer', 'Dereferences a pointer', 'Deletes a pointer', 'Compares pointers'],
      correctAnswer: 'Dereferences a pointer',
      explanation: 'The * operator is used to dereference a pointer, accessing the value it points to',
      timeLimit: 30,
      points: 15
    },
    {
      id: uuidv4(),
      type: 'concept',
      difficulty: 'medium',
      language: 'python',
      title: 'Time Complexity',
      content: 'What is the time complexity of searching for an element in a sorted array using binary search?',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
      correctAnswer: 'O(log n)',
      explanation: 'Binary search has O(log n) time complexity as it halves the search space in each iteration',
      timeLimit: 30,
      points: 15
    },
    {
      id: uuidv4(),
      type: 'os',
      difficulty: 'hard',
      language: 'java',
      title: 'Operating Systems',
      content: 'Which scheduling algorithm can cause starvation?',
      options: ['Round Robin', 'First Come First Served', 'Shortest Job First', 'Priority Scheduling'],
      correctAnswer: 'Priority Scheduling',
      explanation: 'Priority scheduling can cause starvation when high-priority processes keep arriving',
      timeLimit: 30,
      points: 20
    }
  ];

  async generateBattleQuestions(): Promise<Question[]> {
    // For now, return a random selection of 10 questions
    const shuffled = [...this.sampleQuestions].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, 10);
  }

  async getQuestionsByLanguage(language: ProgrammingLanguage): Promise<Question[]> {
    return this.sampleQuestions.filter(q => q.language === language);
  }

  async getQuestionsByDifficulty(difficulty: QuestionDifficulty): Promise<Question[]> {
    return this.sampleQuestions.filter(q => q.difficulty === difficulty);
  }

  async getQuestionById(id: string): Promise<Question | null> {
    return this.sampleQuestions.find(q => q.id === id) || null;
  }

  // This would integrate with Google Gemini for generating questions
  async generateQuestion(
    language: ProgrammingLanguage,
    difficulty: QuestionDifficulty,
    type: QuestionType
  ): Promise<Question> {
    // Placeholder - would use AI to generate questions
    return {
      id: uuidv4(),
      type,
      difficulty,
      language,
      title: 'AI Generated Question',
      content: 'This would be generated by AI',
      options: ['Option 1', 'Option 2', 'Option 3', 'Option 4'],
      correctAnswer: 'Option 1',
      explanation: 'AI generated explanation',
      timeLimit: 30,
      points: difficulty === 'easy' ? 10 : difficulty === 'medium' ? 15 : 20
    };
  }
}